import {createContext,useContext} from 'react'
export type Lang='zh'|'en'
const zh={dashboard:'概览',docker:'Docker',websites:'网站与反代',services:'系统服务',tasks:'任务与审计',alerts:'监控告警',security:'账号安全',cpu:'CPU 使用率',memory:'内存',disk:'磁盘',load:'系统负载',containers:'容器',running:'运行中',serviceHealth:'服务状态',recentTasks:'最近任务',insecure:'当前通过 HTTP 明文访问，账号与会话可能被截获。建议尽快绑定域名并启用 HTTPS。',logout:'退出登录',refresh:'刷新',start:'启动',stop:'停止',restart:'重启',remove:'删除',install:'一键安装',installed:'已安装',missing:'未安装',active:'运行中',inactive:'未运行',apply:'应用配置',source:'配置文件',proxy:'反代目标',noData:'暂无数据',confirmDelete:'这是不可恢复的操作。再次输入 DELETE 以确认：',username:'用户名',password:'密码',totp:'动态验证码',login:'登录',firstLogin:'首次登录必须修改账号信息',newUsername:'新用户名',newPassword:'新密码（至少 10 位）',save:'保存',setupTOTP:'配置 TOTP',language:'English'} as const
const en:Record<keyof typeof zh,string>={dashboard:'Overview',docker:'Docker',websites:'Sites & Proxy',services:'Services',tasks:'Tasks & Audit',alerts:'Alerts',security:'Account Security',cpu:'CPU usage',memory:'Memory',disk:'Disk',load:'Load average',containers:'Containers',running:'running',serviceHealth:'Service health',recentTasks:'Recent tasks',insecure:'This panel is using plain HTTP. Credentials and sessions may be intercepted. Bind a domain and enable HTTPS as soon as possible.',logout:'Sign out',refresh:'Refresh',start:'Start',stop:'Stop',restart:'Restart',remove:'Delete',install:'Install',installed:'Installed',missing:'Missing',active:'Active',inactive:'Inactive',apply:'Apply config',source:'Source file',proxy:'Proxy target',noData:'No data',confirmDelete:'This cannot be undone. Type DELETE to confirm:',username:'Username',password:'Password',totp:'TOTP code',login:'Sign in',firstLogin:'You must change your account on first login',newUsername:'New username',newPassword:'New password (10+ chars)',save:'Save',setupTOTP:'Set up TOTP',language:'中文'}
const messages={zh,en}
export type MessageKey=keyof typeof zh
export const I18n=createContext({lang:'zh' as Lang,setLang:(_:Lang)=>{},t:(k:MessageKey)=>messages.zh[k] as string})
export const useI18n=()=>useContext(I18n)
export function translator(lang:Lang){return (key:MessageKey)=>messages[lang][key]}
